name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Trigger the workflow on push to the main branch

env:
  ECR_REGISTRY: ${{ env.AWS_ECR_REGISTRY }}  # Your AWS ECR registry URL, stored in GitHub secrets
  ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY_NAME }}          # ECR repository name
  IMAGE_TAG: latest                             # You can dynamically set this as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: staging  # Specify that this job is for the 'staging' environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f CalculatorService/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Logout from Docker
      run: docker logout $ECR_REGISTRY
